### ISSUE TITLE
javascript includes

### ISSUE THREAD

**Issue by lgwapnitsky** [robulouski/voidy-bootstrap#7]
Having issue with including javascript. I've set my pelicanconf.py to have CUSTOM_SCRIPTS_BASE to point to my custom file, which contains the following:

    <script src='/js/mb-comingsoon/jquery.mb-comingsoon.js"></script>
    <script type="text/javascript">
        $(function () {
            var $section = $('section');
            $(window).on("resize", function () {
                var dif = Math.max($(window).height() - $section.height(), 0);
                var padding = Math.floor(dif / 2) + 'px';
                $section.css({ 'padding-top': padding, 'padding-bottom': padding });
            }).trigger("resize");
            $('#myCounter').mbComingsoon({ expiryDate: new Date(2015, 0, 1, 9, 30), speed:100 });
            setTimeout(function () {
                $(window).resize();
            }, 200);
        });
    </script>

The script appears as part of my page load, but the div that I setup

    <div id="myCounter"></div>

never shows on the page. Am I missing something?

Thanks
Larry

**Comment by robulouski** [comment]
How are you setting up that "myCounter" div?  How is it getting into the page?

What are you trying to achieve? If that JavaScript is present in the page source it's likely to be a problem with the JavaScript and not the theme.

**Comment by lgwapnitsky** [comment]
adding it in via non-indented markdown.

I've tried a few different scripts with the same results.  code samples are
direct from each script's site

**Comment by robulouski** [comment]
The problem is with your HTML.  There's a mismatched quote in the first script block for starters.

Pelican copies the theme's [static files into a "theme" subdirectory.](http://docs.getpelican.com/en/3.5.0/themes.html#structure)

So I believe the first line should look something like this:

    <script src="/theme/js/mb-comingsoon/jquery.mb-comingsoon.js"></script>

**Comment by lgwapnitsky** [comment]
damn quotes! :)  Thanks!
